name: Test and Release

on:
  push:
    branches:
      - saga
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ">=24.18.1 <25"
          cache: "npm"

      - name: Install NPM version specified in package.json
        uses: ./.github/actions/install-npm

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Check source code with eslint
        run: npx eslint ./

      - name: Check if source code is properly formatted
        run: npx prettier -c ./

      - name: Run tests
        run: npm test

      - name: Export to-be released version
        run: |
          npx semantic-release --dry-run > semantic-release.out
          echo "RELEASE_VERSION=$(cat semantic-release.out | grep -i 'The next release version is' | awk '{print $11}')" >> $GITHUB_ENV
          cat semantic-release.out

      - name: Ensure it builds
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          npm run build
          cp -L -r ./static ./build

      - name: Upload build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build
          path: ./build
          retention-days: 7

      - name: Semantic release
        if: env.RELEASE_VERSION !=  ''
        id: semantic-release
        run: npx semantic-release
